/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.io.BufferedReader;
import java.io.FileReader;
import edd.Grafo;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.graphstream.graph.*;
import org.graphstream.graph.implementations.*;

/**
 *
 * @author manch
 */
public class InterfazPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form InterfazPrincipal
     */
    public Grafo grafoCreado = new Grafo();
    public Graph grafoMostrar = new SingleGraph("Grafo");
    public InterfazPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SelectFile = new javax.swing.JButton();
        Acciones = new javax.swing.JLabel();
        SaveData = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        Proyect = new javax.swing.JLabel();
        College = new javax.swing.JLabel();
        Names = new javax.swing.JLabel();
        Menu = new javax.swing.JLabel();
        Content = new javax.swing.JTabbedPane();
        View = new javax.swing.JPanel();
        ViewGrafo = new javax.swing.JButton();
        Add = new javax.swing.JPanel();
        AñadirUsuarios = new javax.swing.JTextField();
        Ejemplo = new javax.swing.JLabel();
        AddButton = new javax.swing.JButton();
        Erase = new javax.swing.JPanel();
        EraseButton = new javax.swing.JButton();
        UsuariosList = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        MultiplesUsuarios1 = new javax.swing.JComboBox<>();
        MultiplesUsuarios2 = new javax.swing.JComboBox<>();
        Conectar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SelectFile.setText("Cargar Archivo");
        SelectFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectFileActionPerformed(evt);
            }
        });

        Acciones.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Acciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Acciones.setText("Acciones");

        SaveData.setText("Guardar Cambios");
        SaveData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveDataActionPerformed(evt);
            }
        });

        Exit.setText("Salir");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        Proyect.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Proyect.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Proyect.setText("PROYECTO 1 - ESTRUCTURA DE DATOS");

        College.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        College.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        College.setText("UNIVERSIDAD METROPOLITANA");

        Names.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Names.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Names.setText("Elias Fung - Darío Fernández");

        Menu.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Menu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Menu.setText("Menu Principal");

        ViewGrafo.setText("Ver Grafo");
        ViewGrafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewGrafoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ViewLayout = new javax.swing.GroupLayout(View);
        View.setLayout(ViewLayout);
        ViewLayout.setHorizontalGroup(
            ViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewLayout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addComponent(ViewGrafo)
                .addContainerGap(264, Short.MAX_VALUE))
        );
        ViewLayout.setVerticalGroup(
            ViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(ViewGrafo)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        Content.addTab("Ver", View);

        AñadirUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AñadirUsuariosActionPerformed(evt);
            }
        });

        Ejemplo.setText("Ejemplo: @Xx_Destroyer_xX");

        AddButton.setText("Agregar");
        AddButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout AddLayout = new javax.swing.GroupLayout(Add);
        Add.setLayout(AddLayout);
        AddLayout.setHorizontalGroup(
            AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(AddButton)
                .addGap(18, 18, 18)
                .addComponent(AñadirUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Ejemplo, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        AddLayout.setVerticalGroup(
            AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AñadirUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ejemplo)
                    .addComponent(AddButton))
                .addContainerGap(186, Short.MAX_VALUE))
        );

        Content.addTab("Añadir", Add);

        EraseButton.setText("Borrar");
        EraseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EraseButtonMouseClicked(evt);
            }
        });

        UsuariosList.setToolTipText("");
        UsuariosList.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                UsuariosListFocusGained(evt);
            }
        });
        UsuariosList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuariosListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EraseLayout = new javax.swing.GroupLayout(Erase);
        Erase.setLayout(EraseLayout);
        EraseLayout.setHorizontalGroup(
            EraseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EraseLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(EraseButton)
                .addGap(18, 18, 18)
                .addComponent(UsuariosList, 0, 120, Short.MAX_VALUE)
                .addGap(321, 321, 321))
        );
        EraseLayout.setVerticalGroup(
            EraseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EraseLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(EraseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EraseButton)
                    .addComponent(UsuariosList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(185, Short.MAX_VALUE))
        );

        Content.addTab("Borrar", Erase);

        jLabel1.setText("Primer Usuario");

        jLabel2.setText("Segundo Usuario");

        MultiplesUsuarios1.setToolTipText("");
        MultiplesUsuarios1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                MultiplesUsuarios1FocusGained(evt);
            }
        });

        MultiplesUsuarios2.setToolTipText("");
        MultiplesUsuarios2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                MultiplesUsuarios2FocusGained(evt);
            }
        });

        Conectar.setText("Conectar Usuarios");
        Conectar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConectarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Conectar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MultiplesUsuarios1, 0, 120, Short.MAX_VALUE)
                            .addComponent(MultiplesUsuarios2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(303, 303, 303))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(MultiplesUsuarios1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(MultiplesUsuarios2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(Conectar)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        Content.addTab("Conectar", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SelectFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Acciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SaveData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Content, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Proyect, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(College, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Names, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(347, 347, 347)
                        .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Proyect)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(College)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Names)
                .addGap(35, 35, 35)
                .addComponent(Menu)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(Acciones)
                        .addGap(18, 18, 18)
                        .addComponent(SelectFile)
                        .addGap(18, 18, 18)
                        .addComponent(SaveData)
                        .addGap(107, 107, 107)
                        .addComponent(Exit))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Content, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SelectFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectFileActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);

        FileNameExtensionFilter imgFilter = new FileNameExtensionFilter("TXT Files", "txt", "csv");
        fileChooser.setFileFilter(imgFilter);

        int result = fileChooser.showOpenDialog(this);
        File fileName = fileChooser.getSelectedFile();
        BufferedReader reader = null;
        try {
            reader = new BufferedReader(new FileReader(fileName.getAbsolutePath()));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(InterfazPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        String line;
        try {
            while ((line = reader.readLine()) != null) {
                
                if(line.equals("usuarios")) {
                    
                    // Parse users
                    while(!(line = reader.readLine()).equals("relaciones")) {
                        grafoCreado.addVertex(line);
                        Node nodoGrafoMostrar = grafoMostrar.addNode(line);
                        nodoGrafoMostrar.setAttribute("ui.style", "text-size: 25px; size-mode: fit; shape: rounded-box; fill-color: white; stroke-mode: plain; padding: 5px, 4px;");
                        nodoGrafoMostrar.setAttribute("ui.label",  line);
                    }
                    
                } else if(line.equals("relaciones")) {
                    
                    // Parse relations
                    while((line = reader.readLine()) != null) {
                        
                        StringTokenizer st = new StringTokenizer(line, ",");
                        
                        String src = st.nextToken().trim();
                        String dest = st.nextToken().trim();
                        
                        grafoCreado.addEdge(src, dest);
                        grafoMostrar.addEdge("1", src, dest, true);
                        // Find first comma
                        //int commaIndex = line.indexOf(',');

                        // Extract source and dest substrings 
                        //String src = line.substring(0, commaIndex).trim();
                        //String dest = line.substring(commaIndex + 1).trim();

                        // Add edge
                        //grafoCreado.addEdge(src, dest);
                        //grafoMostrar.addEdge(src + dest, src, dest, true);
                    }
                }
            }       } catch (IOException ex) {
            Logger.getLogger(InterfazPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            reader.close();
        } catch (IOException ex) {
            Logger.getLogger(InterfazPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }



    }//GEN-LAST:event_SelectFileActionPerformed

    private void SaveDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaveDataActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        System.exit(WIDTH);
    }//GEN-LAST:event_ExitActionPerformed

    private void AñadirUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AñadirUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AñadirUsuariosActionPerformed

    private void ViewGrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewGrafoActionPerformed
        // TODO add your handling code here:
        grafoMostrar.display();
    }//GEN-LAST:event_ViewGrafoActionPerformed

    private void EraseButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EraseButtonMouseClicked
        // TODO add your handling code here:
        grafoCreado.removeVertex((String) UsuariosList.getSelectedItem());
        JOptionPane.showMessageDialog(null, "Usuario borrado de Grafo:");
        grafoMostrar.removeNode((String) UsuariosList.getSelectedItem());
        UsuariosList.requestFocus();
    }//GEN-LAST:event_EraseButtonMouseClicked

    private void UsuariosListFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UsuariosListFocusGained
        // TODO add your handling code here:
        UsuariosList.removeAllItems();
        for (int i = 0; i <= grafoCreado.getListOfUsers().getSize() -1; i++) {
            UsuariosList.addItem(grafoCreado.getListOfUsers().get(i));
        }
    }//GEN-LAST:event_UsuariosListFocusGained

    private void UsuariosListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuariosListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuariosListActionPerformed

    private void MultiplesUsuarios1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MultiplesUsuarios1FocusGained
        // TODO add your handling code here:
        MultiplesUsuarios1.removeAllItems();
        for (int i = 0; i <= grafoCreado.getListOfUsers().getSize() -1; i++) {
            MultiplesUsuarios1.addItem(grafoCreado.getListOfUsers().get(i));
        }
    }//GEN-LAST:event_MultiplesUsuarios1FocusGained

    private void MultiplesUsuarios2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MultiplesUsuarios2FocusGained
        // TODO add your handling code here:
        MultiplesUsuarios2.removeAllItems();
        for (int i = 0; i <= grafoCreado.getListOfUsers().getSize() -1; i++) {
            MultiplesUsuarios2.addItem(grafoCreado.getListOfUsers().get(i));
        }
    }//GEN-LAST:event_MultiplesUsuarios2FocusGained

    private void ConectarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConectarMouseClicked
        // TODO add your handling code here:
        if (!grafoCreado.checkEdge((String) MultiplesUsuarios1.getSelectedItem(), (String) MultiplesUsuarios2.getSelectedItem())){
            grafoCreado.addEdge((String) MultiplesUsuarios1.getSelectedItem(), (String) MultiplesUsuarios2.getSelectedItem());
            grafoMostrar.addEdge("1", (String) MultiplesUsuarios1.getSelectedItem(), (String) MultiplesUsuarios2.getSelectedItem(), true);
        }
    }//GEN-LAST:event_ConectarMouseClicked

    private void AddButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddButtonMouseClicked
        // TODO add your handling code here:
        int check = 0;
        if ("".equals(AñadirUsuarios.getText().trim())) {
            JOptionPane.showMessageDialog(null, "Ingrese Usuario:");
            AñadirUsuarios.requestFocus();
        } else {
            // Chequear si Existe Usuario
            if (validateUser(AñadirUsuarios.getText())) {
                check = CheckUsuario(AñadirUsuarios.getText());
                if (check == 1) {
                    JOptionPane.showMessageDialog(null, "El Usuario Existe, Ingrese otro nombre:");
                    AñadirUsuarios.requestFocus();
                } else {
                    grafoCreado.addVertex(AñadirUsuarios.getText());
                    Node nodo = grafoMostrar.addNode(AñadirUsuarios.getText());
                    JOptionPane.showMessageDialog(null, "Usuario añadido al Grafo:");
                    nodo.setAttribute("ui.style", "text-size: 25px; size-mode: fit; shape: rounded-box; fill-color: white; stroke-mode: plain; padding: 5px, 4px;");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Faltó el @");
                AñadirUsuarios.requestFocus();
            }
        }
    }//GEN-LAST:event_AddButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }
    public int CheckUsuario(String usuario) {
            int check = 0;
            for (int i = 0; i <= grafoCreado.getListOfUsers().getSize() - 1; i++) {
                if (usuario.equals(grafoCreado.getListOfUsers().get(i))) {
                    check = 1;
                    break;
                }
            }
            return check;
        }

        public boolean validateUser(String input) {
            String[] words = input.split("\\s+");
            String firstWord = words[0];
            return firstWord.startsWith("@");
        }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Acciones;
    private javax.swing.JPanel Add;
    private javax.swing.JButton AddButton;
    private javax.swing.JTextField AñadirUsuarios;
    private javax.swing.JLabel College;
    private javax.swing.JButton Conectar;
    private javax.swing.JTabbedPane Content;
    private javax.swing.JLabel Ejemplo;
    private javax.swing.JPanel Erase;
    private javax.swing.JButton EraseButton;
    private javax.swing.JButton Exit;
    private javax.swing.JLabel Menu;
    private javax.swing.JComboBox<String> MultiplesUsuarios1;
    private javax.swing.JComboBox<String> MultiplesUsuarios2;
    private javax.swing.JLabel Names;
    private javax.swing.JLabel Proyect;
    private javax.swing.JButton SaveData;
    private javax.swing.JButton SelectFile;
    private javax.swing.JComboBox<String> UsuariosList;
    private javax.swing.JPanel View;
    private javax.swing.JButton ViewGrafo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
